cart/urls.py
from django.urls import path,   path
from .views import (
    add,
    remove,
    show,

)
app_name = 'cart'
urlpatterns = [
    path('add/<int:id>', add, name='cart_add'),
    path('remove/<int:id>', remove, name='cart_remove'),
    path('show/', show, name='cart_show'),
]

ecom/urls.py
from django.contrib import admin
from . import settings
from django.urls import path, re_path
from home.views import home
from django.urls import include
from django.conf.urls.static import static
from register.views import login_view, forgot_pass_view
from search.views import search
urlpatterns = [
    path('', home, name='home'),
    path('admin/', admin.site.urls),
    path('products/', include('products.urls'), name='products'),
    path('accounts/', include('register.urls'), name='register'),
    path('dashboard/', include('dashboard.urls'), name='shopdashboard'),
    path('search/', include('search.urls'), name='search'),
    path('search-page/', search),
    path('shop/', include('shop.urls')),
    path('ajax/', include('order.urls')),
    path('khata/', include('khata.urls'), name='khata'),
    path('burak/', include('driver.urls'), name='driver'),
    path('', include('pwa.urls')), 

]
urlpatterns += static(settings.STATIC_URL, document_root=settings.STATICFILES_DIRS)
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

order/urls.py
from django.urls import path, re_path
from .views import add, clear_view, show, delete, thankyou, user_order, order_detail
app_name = 'order'
urlpatterns = [

    path('add', add, name='add'),
    path('delete/<int:pk>/', delete, name='delete'),
    path('clear/', clear_view, name='clear'),
    path('cart/', show, name='show'),
    path('cart/thankyou', thankyou, name='thankyou'),
    path('orders/', user_order, name='oips'),
    path('order/<int:pk>/', order_detail, name='detail'),

]

search/urls.py
from django.urls import path, re_path

from .views import SearchProductView
        
app_name = 'search'
urlpatterns = [
    re_path(r'^$', SearchProductView.as_view(), name='query'),
]

home/models.py
from django.db import models

# Create your models here.

home/views.py
from django.shortcuts import render, get_object_or_404
from django.contrib.auth.models import User
from django.contrib.auth.decorators import login_required
from products.models import Product, Category
from order.cart import Cart
from shop.models import Shop


@login_required
def home(request):
    cart = Cart(request.session)
    no = cart.unique_count.real
    qs = Product.objects.all()
    cat_list = Category.objects.all()
    context = {
        'no_obj':no,
        "cat_list": cat_list
    }

    template_name= 'home.html'
    return render(request, template_name, context)

home/templates/home.html
{% extends 'base.html' %}
{% load static %}
{% block content %}
<body>


    <div class="appHeader">
                <div class="left">
                    <a href="#" class="headerButton" style="color: rgb(255, 166, 0);">
                        <ion-icon name="chevron-back-outline"></ion-icon>
                    </a>
                </div>
<div>
                    <img src="{% static 'assets/img/logopk.png' %}" alt="image" class="imaged w200">
                </div>                
                <div class="right">
                    <a href="javascript:;" class="headerButton toggle-searchbox" style="color: rgb(216, 142, 5);">
                        <ion-icon name="search-outline"></ion-icon>
                    </a>
                </div>
    </div>

    <!-- Search Component -->
    <div id="search" class="appHeader">
        <form class="search-form" method='GET' action='{% url "search:query" %}'>{% csrf_token %}
            <div class="form-group searchbox">
                <input type="text" class="form-control" placeholder="Search..." required name='q' aria-label="Search">
                <button class="btn" type="submit">
                <i class="input-icon">
                    <ion-icon name="search-outline"></ion-icon>
                </i>
                </button>
                <a href="javascript:;" class="ml-1 close toggle-searchbox">
                    <ion-icon name="close-circle"></ion-icon>
                </a>
            </div>
        </form>
    </div>
    <!-- * Search Component -->


    <div id="appCapsule">


<!-- 
        <div class="section full mb-3">
                <div class="section-title">Categories</div>

                <div class="carousel-multiple owl-carousel owl-theme">
                    {% for cat in cat_list %}
                        <div class="item">
                            <a href = "{{cat.get_absolute_url}}">
                                <div class="card bg-dark text-black text-center">
                                    {% if cat.thumbnail %}
                                    <img src="{{cat.thumbnail.url}}" class="card-img overlay-img" alt="image">
                                    {% endif %}
                                    <div class="card-img-overlay">
                                        <h1 class="card-title" style="font-family: Noto Nastaliq Urdu Draft;">{{cat.category}}</h1>
                                    </div>
                                </div>
                            </a>
                        </div>
                    {% endfor %}
                    
                </div>
        </div> -->


        <div class="section full mb-3">
            <div class="section-title" style="font-size: large;">Categories</div>
                <div class="row" style="padding-top: 20px;">
                {% for cat in cat_list %}
                        <div class="col-6">
                        <div class="card product-card">
                            <div class="card-body">
                                <a href = "{{cat.get_absolute_url}}">
                                <img src="{{cat.thumbnail.url}}" class="image " alt="product image">
                                <div class="" style="text-align: center;">
                                    <h1 style="font-family: Noto Nastaliq Urdu Draft; font-size: 30px;">{{cat.category}}</h1>
                                </div>
                                </a>
                            </div>
                        </div>
                    </div>
                    {% if forloop.counter|divisibleby:2 %}
                        </div>
                        <div class="row" style="padding-top: 20px;">

                    {% endif %}
                {% endfor %}
                </div>
        </div>
    
    </div>


    {% include 'bottom.html' %}


</body>


















{% endblock %}